default: &default
  adapter: postgresql
  encoding: unicode

development:
  adapter: postgresql
  database: library_development
  username: library_development
  password: library_development
  encoding: unicode
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: library_test
  username: library_test
  password: library_test
  encoding: unicode
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: library_production
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
