default: &default
  adapter: postgresql
  encoding: unicode

development:
  adapter: postgresql
  database: library_development
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  encoding: unicode
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: library_test
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  encoding: unicode
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: library_production
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
