default: &default
  adapter: postgresql
  encoding: unicode

development:
  adapter: postgresql
  database: library_development
  username: maanavshah
  password: maanavshah
  encoding: unicode
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: library_test
  username: maanavshah
  password: maanavshah
  encoding: unicode
  host: localhost
  pool: 5
